PROG = getfundSEC
LIB = getfundSEC.a
DEF = /usr/local/include

# MYSQL_DIR = /usr/lib64
# MYSQL_FLAGS = -lz -lcrypt -lm -lssl -lcrypto
# MLIB = $(MYSQL_DIR)/libmysqlclient.so $(MYSQL_FLAGS)

# XLIB = /usr/local/lib64/invlib.a /usr/local/lib64/dbylib.a /usr/local/lib64/shslib.a

XLIB = /usr/local/lib64/invlib.a /usr/local/lib64/dbylib.a /usr/local/lib64/shslib.a  \
		/usr/local/lib/libmysqlclient.a \
		/usr/local/lib/libcrypto.a \
		/usr/local/lib/libxlsxwriter.a \
		/usr/local/lib/libssl.a \
		/usr/local/Cellar/zlib/1.3.1/lib/libz.a


#		/usr/local/lib64/rptlib.a \
# libta_lib.a

PRG = /usr/local/bin/$(PROG)

FILES = \
	$(LIB)(getfundSEC.o)	\
	$(LIB)(getargs.o)		\
	$(LIB)(EachFundamental.o)	\
	$(LIB)(EachStock.o)

.SILENT:

$(PRG): $(LIB) $(XLIB)
	echo "using gcc to load $(PRG)"
	gcc -o $(PRG) $(LIB) $(XLIB) $(MLIB)

$(LIB): $(FILES)

$(FILES): getfundSEC.h $(DEF)/shslib.h $(DEF)/dbylib.h $(DEF)/fileinvest.h $(DEF)/invlib.h

python:
	cp -pv getfundSEC.py /usr/local/bin/getfundSEC.py
	cp -pv FCF_Stats.py /usr/local/bin/FCF_Stats.py

clean:
	rm -f $(LIB)

all:
	make clean
	make
	make python

.PRECIOUS: $(LIB)

