
PROG=fundamentals
DEF = /usr/local/include

LIB = fundamentals_64.a
# XLIB = /usr/local/lib64/invlib.a /usr/local/lib64/dbylib.a /usr/local/lib64/weblib.a /usr/local/lib64/shslib.a  /usr/lib64/libmysqlclient.so /usr/local/lib64/libxlsxwriter.a  -lz -lssl -luuid -lcrypto -lm

XLIB = /usr/local/lib64/invlib.a /usr/local/lib64/dbylib.a \
		/usr/local/lib64/weblib.a  \
		/usr/local/lib64/shslib.a  \
		/usr/local/lib/libmysqlclient.a \
		/usr/local/lib64/rptlib.a \
		/usr/local/lib/libcrypto.a \
		/usr/local/lib/libxlsxwriter.a \
		/usr/local/lib/libssl.a \
		/usr/local/Cellar/zlib/1.3.1/lib/libz.a

WEBDIR = /Users/tms/Sites/shs_stocks

# libta_lib.a


PRG =$(WEBDIR)/$(PROG).cgi

FILES = \
	$(LIB)(fundamentals.o)	\
	$(LIB)(GetInput.o)

.SILENT:

$(PRG): $(LIB) $(XLIB)
	echo "using gcc to load $(PRG)"
	gcc $(LDFLAGS) -o $(PRG) $(LIB) $(XLIB)

$(LIB): $(FILES)

$(FILES): fundamentals.h $(DEF)/shslib.h $(DEF)/weblib.h $(DEF)/invlib.h  $(DEF)/dbylib.h $(DEF)/fileinvest.h

css:
	cp -pv fundamentals.css $(WEBDIR)/fundamentals.css

clean:
	rm -f $(LIB)

all:
	make clean
	make
	make css

.PRECIOUS: $(LIB)
